import { Anuphan, Alexandria } from "next/font/google";
import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/navbar";

const anuphan = Anuphan({
  subsets: ["thai"],
  variable: '--font-anuphan',
  display: "swap",
});

const alexandria = Alexandria({
  subsets: ["latin"],
  variable: '--font-alexandria',
  display: "swap",
});

export const metadata: Metadata = {
  title: "Sim DSS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${anuphan.variable} ${alexandria.variable}`}>
      <body className="font-sans antialiased">
      <Navbar/>
        {children}
      </body>
    </html>
  );
}