import type { Metadata } from "next";
import { Anuphan, Alexandria } from "next/font/google";
import "./globals.css";

const anuphan = Anuphan({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700"],
  variable: '--font-anuphan'
});

const alexandria = Alexandria({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700"],
  variable: '--font-alexandria'
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${anuphan.variable} ${alexandria.variable}`}>
      <body className="font-sans antialiased">
        {children}
      </body>
    </html>
  );
}